version: "3"
services:

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  statsd:
    image: prom/statsd-exporter:v0.18.0
    entrypoint: /bin/statsd_exporter
    command:
      - "--statsd.mapping-config=/etc/statsd-exporter/conf.yaml"
    expose:
      - 9125
      - 9102
    ports:
      - 9125:9125
      - 9102:9102 # Visit http://localhost:9102/metrics to see metrics in Prometheus format
    networks:
      - ratelimit-network
    volumes:
      - ./examples/prom-statsd-exporter/conf.yaml:/etc/statsd-exporter/conf.yaml

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - statsd
    networks:
      - ratelimit-network
    volumes:
      - ./examples/ratelimit/config:/data/ratelimit/config
    environment:
      - USE_STATSD=true
      - STATSD_HOST=statsd
      - STATSD_PORT=9125
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=FILE
      # - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      # - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      # - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

  ratelimit-xds-config-server:
    image: ratelimit-xds-config-server:latest
    build:
      context: examples/xds-sotw-config-server
      dockerfile: Dockerfile
    command: ["-nodeID", "test-node-id", "-port", "18000", "-debug", "true"]
    expose:
      - 18000
    networks:
      - ratelimit-network
    profiles:
      - xds-config

  # Place your envoy config at ./examples/envoy/proxy.yaml
  envoy-tests:
    image: envoyproxy/envoy-dev:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./examples/envoy/proxy.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - 19637
    ports:
      - 19637:19637

  agnostic-tests:
    image: ubuntu:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - ratelimit-network

  agnostic-tests-2:
    image: ubuntu:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - ratelimit-network

networks:
  ratelimit-network:
